# Generated by Django 5.0.7 on 2024-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlateDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_plate_image', models.ImageField(upload_to='face_Detection_images/')),
                ('car_image', models.ImageField(upload_to='face_detection_image/')),
            ],
        ),
    ]
